package fr.ujm.tse.lt2c.satin.interfaces;

import org.apache.log4j.Logger;

/**
 * Baseline of the reasoner. Compute the new triples generated by a rule
 * e.g. <c1 rdfs:subClassOf c2> & <x rdf:type c1> => <x rdf:type c2>
 * 
 * @author Jules Chevalier
 */
public interface RuleRun extends Runnable {

    @Override
    void run();

    /**
     * @return the logger of the class
     */
    Logger getLogger();

}
