package fr.ujm.tse.lt2c.satin.interfaces;

import org.apache.log4j.Logger;


/**
 * @author jules
 * Baseline of the reasoner. Compute the new triples generated by a rule
 * e.g. <c1 rdfs:subClassOf c2> & <x rdf:type c1> => <x rdf:type c2>
 */
public interface RuleRun extends Runnable{
	
	public void run();
	
	/**
	 * @return the logger of the class
	 */
	public Logger getLogger();

}
